export const education = [
  {
    id: 0,
    img: "https://firebasestorage.googleapis.com/v0/b/flexi-coding.appspot.com/o/Kiit.jpeg?alt=media&token=3839d520-c59d-4341-ad8f-0980c98de4dd",
    school: "Kalinga Institute of Industrial Technology, Bhubaneswar",
    date: "Oct 2021 - Sep 2025",
    grade: "8.71 CGPA",
    desc: "I am currently pursuing a Bachelor's degree in Computer Science and Engineering at Kalinga Institute of Industrial Technology, Bhubaneswar. I have completed 4 semesters and have a CGPA of 8.71. I have taken courses in Data Structures, Algorithms, Object-Oriented Programming, Database Management Systems, Operating Systems, and Computer Networks, among others. I am also a member of the Google Developers Student Club (GDSC) at KIIT, where I am learning and working on exciting projects with a team of talented developers.",
    degree: "Bachelor of Technology - BTech, Computer Science and Engineering",
  },
  {
    id: 1,
    img: "https://firebasestorage.googleapis.com/v0/b/flexi-coding.appspot.com/o/methodist.png?alt=media&token=018a1b18-e2dd-4f34-8855-cff1b6b69fd3",
    school: "Methodist School, Dankuni",
    date: "Apr 2019 - Apr 2025",
    grade: "88.2%",
    desc: "I completed my class 12 high school education at Methodist School, Dankuni, where I studied Science with Computer Science.",
    degree: "ISC(XII), Science with Computer",
  },
  {
    id: 2,
    img: "https://firebasestorage.googleapis.com/v0/b/flexi-coding.appspot.com/o/methodist.png?alt=media&token=018a1b18-e2dd-4f34-8855-cff1b6b69fd3",
    school: "Methodist School, Dankuni",
    date: "Apr 2017 - Apr 2019",
    grade: "92.3%",
    desc: "I completed my class 10 education at Methodist School, Dankuni, where I studied Science with Computer Application.",
    degree: "ICSC(X), Science with Computer",
  },
];

export const experiences = [
  {
    id: 0,
    img: "Doko",
    role: "Web Developer",
    company: "Dokolany Cargo Management Pvt Ltd.",
    date: "Nov 2022 - Present",
    desc: ["Developed the core concept of our project — Cargo Details Page. This critical component, where individuals collaborated, serves as the focal point for intricate Package Dimension Calculations.",
      "Implemented Tanstack Query for data fetching, leading to 80% reduction in loader time.",
      "Salesync : Internal portal for sales and business teams, developed entire frontend (React.js). Integrated real-time communication through live chat using Socket.io.",
      "Created Rest API for role, internal management (Node, Express, MongoDB, Mongoose)",
      "Salesync : Integrated Socket.io for real-time communication",
      "Created a custom middleware for all API to authenticate the user and Created mail templates using EJS"],
    skills: [
      "HTML",
      "CSS",
      "Bootstrap",
      "Material UI",
      "React",
      "Redux",
      "Tanstack-Query",
      "Node Js",
      "Express",
      "MongoDB",
      "Socket IO",
      "Mongoose",
    ],
    doc: "https://media.licdn.com/dms/image/D4D2DAQFlp60ZqHuaFQ/profile-treasury-image-shrink_1280_1280/0/1691180828512?e=1692381600&v=beta&t=mM5Y_NE5EPlQhez5FAN6NLVSKcO_Ojt_9Gq3mnFGkAQ",
  },
  {
    id: 1,
    img: "Nlc",
    role: "Graduate Trainee",
    company: "NLC India Limited",
    date: "Mar 2022 - Nov 2022",
    desc: ["Voluntarily involved in creation of some webpages wherein employees would be able to raise complaints and automatic house allocation for employees in NLC India (HTML,CSS, Bootstrap).",
    ],
    skills: [
      "HTML",
      "CSS",
      "Javascript",
    ],
    doc: "https://firebasestorage.googleapis.com/v0/b/buckoid-917cf.appspot.com/o/Screenshot%20from%202023-05-28%2023-20-46.png?alt=media&token=5570f995-e8f4-4f12-bb2f-73bcf4b20730",
  },


];
