export const ProfessinalSummaryPoints = [
 "Proficient in building and deploying full-stack web applications using the MERN stack (MongoDB, Express.js, React.js, Node.js).",
 "Experienced in end-to-end development, from conceptualization and design to deployment and maintenance.",
 "Skilled in implementing client-side routing with React Router.",
 "Extensive experience with React.js, including functional components, hooks, state management (using Context API, Redux), and performance optimization.",
 "Experienced in optimizing front-end performance using techniques like lazy loading, code splitting, and memoization.",
 "Strong understanding of modern JavaScript (ES6+) and TypeScript.",
 "Expertise in managing application state using Redux, Context API, and TanStack Query.",
 "Expertise in creating responsive and user-friendly interfaces using CSS frameworks like Bootstrap, Material-UI, and custom CSS/Sass.",
 "Skilled in developing RESTful APIs and microservices using Node.js and Express.js.",
 "Proficient in building real-time applications using WebSockets and libraries like Socket.io.",
 "Proficient in server-side logic, routing, middleware integration, and authentication mechanisms (JWT, OAuth).",
 "Proficient in using MongoDB for database design, schema modeling, and query optimization.",
 "Experienced with Mongoose for object data modeling (ODM) in Node.js, including schema validation and population.",
 "Proficient in back-end performance tuning, including database indexing, query optimization, and load balancing.",
 "Experienced with Git for version control and GitHub for collaborative development.",
 "Proficient in using CI/CD tools like Azure tools, or GitHub Actions for automated testing and deployment.",
 "Skilled in deploying applications to cloud platforms such as Azure, Heroku, Netlify and Rendered.",
 "Proficient writing the Docker images for both frontend and backend",
 "Proficient in using Docker for containerization for deployment.",
 "Skilled in designing and consuming RESTful APIs, as well as working with GraphQL for flexible and efficient data queries.",
 "Experienced in Agile methodologies and tools like Jira and Click Up for project management and team collaboration.",
 "Proven ability to troubleshoot and resolve complex technical issues across the full stack.",
 "Knowledgeable in implementing security best practices, including data encryption, secure authentication, and protection against common vulnerabilities (e.g., XSS, CSRF, SQL Injection).",
]